remove spaces

diff --git a/wait_for_emulator b/wait_for_emulator
--- a/wait_for_emulator
+++ b/wait_for_emulator
@@ -3,14 +3,14 @@
 devices="2"
 failcounter=0
 until [[ "$devices" =~ "3" ]]; do
-  devices = `adb devices | wc -l`
-  echo "$devices"
-  let "failcounter += 1"
-  if [[ $failcounter -gt 100 ]]; then
-    echo "Failed to start emulator"
-    exit 1
-  fi
-  sleep 10
+   devices=`adb devices | wc -l`
+   echo "$devices"
+   let "failcounter += 1"
+   if [[ $failcounter -gt 100 ]]; then
+      echo "Failed to start emulator"
+      exit 1
+   fi
+   sleep 10
 done
 
 bootanim=""
